.\" Man page for bxcoin-qt
.TH BXCOIN-QT 1 "July 2025" "Bxcoin Core" "User Commands"
.SH NAME
bxcoin-qt \- graphical user interface for Bxcoin Core
.SH SYNOPSIS
bxcoin-qt [options]
.SH DESCRIPTION
bxcoin-qt is the GUI tool to interact with the Bxcoin Core client.
This application allows users to send and receive BX, manage wallets, and view network activity.
.SH OPTIONS
Run \fBbxcoin-qt --help\fR to see available options.
.SH AUTHOR
Bxcoin Developers
